### ISSUE TITLE
why not a scripted field instead?

### ISSUE THREAD

**Issue by jccq** [seadiaz/computed-columns#3]

**Comment by ThomasFlanaghan** [comment]
I am guessing because scripted fields do document level aggregations. this lets you aggregate after the other aggregations. Very useful

**Comment by seadiaz** [comment]
Like @ThomasFlanaghan says, scripted field has document scope and this plugins could be considerer as report scope.

If we have 2 documents:
* Document 1: { a: 10, b: 20 }
* Document 2: { a: 20, b: 30 }

And we want to calculate sum(a) * sum(b) for all documents.

This question it can't be obtained through scripted field, because using scripted field only can obtain sum(a * b).

Replacing values for this plugin: (10 + 20) * (20 + 30) = 1500
Replacing values for scripted fields: (10 * 20) + (20 * 30) = 800
